(test
 (name smoke)
 (libraries ocaml_telegram_eio.telegram ocaml_telegram_eio.tg alcotest yojson)
 (modules smoke))

(test
 (name spec_norm)
 (libraries ocaml_telegram_eio.telegram alcotest)
 (modules spec_norm))

(test
 (name golden)
 (libraries alcotest unix)
 (modules golden))

(executable
 (name update_golden)
 (libraries unix)
 (modules update_golden))

(test
 (name foundation)
 (libraries ocaml_telegram_eio.telegram alcotest)
 (modules foundation))
