(** Media Files Demo - Comprehensive demonstration of media handling

    This example demonstrates all media handling features:
    - Sending photos (file_id, URL)
    - Sending documents
    - Sending videos
    - Photo captions with HTML formatting
    - File downloads (get_file, to_string, to_buffer)
    - Media groups (albums)
    - File info extraction

    Commands:
      /start - Show available features
      /send_photo_url - Send photo from URL
      /send_document - Generate and send a text document
      /send_album - Send a photo album (2 photos)
      /file_info - Get information about the last received file

    Message Handlers:
      - Photos: Extract file_id, show info, offer to resend
      - Documents: Show file info and download content
      - Videos: Show video metadata

    This example has VERBOSE LOGGING enabled for troubleshooting.

    Usage:
      export TELEGRAM_BOT_TOKEN="your_token_here"
      dune exec examples/media_files_demo.exe

    Send photos/documents to the bot to see file handling in action!
*)

open Telegram
open Tg

(* Configure verbose logging with flo *)
let () = Flo.set_level Severity.Debug

module KB = Keyboard

(** Session key for storing last file_id *)
let last_photo_key = Session.make ~name:"last_photo_file_id"
let last_document_key = Session.make ~name:"last_document_file_id"

let () =
  Printexc.record_backtrace true;
  Eio.traceln "=== Media Files Demo Starting ===";

  let token = match Sys.getenv_opt "TELEGRAM_BOT_TOKEN" with
    | Some t -> t
    | None -> Printf.eprintf "TELEGRAM_BOT_TOKEN not set\n"; exit 1
  in

  Eio_main.run @@ fun env ->
  let client = Client.create ~env ~token () in

  Eio.traceln "🤖 Media Files Demo Bot Started";

  let session_store = Session.Memory_store.create () in

  Bot.make ~env ~client
  |> Bot.with_sessions (module Session.Memory_store) session_store

  (* /start - Main menu *)
  |> Bot.command "start" ~desc:"Show available features" (fun ctx _args ->
      let open Bot.Ctx in
      Eio.traceln "[/start] Showing main menu";

      let text =
        "📸 Media Files Demo\n\n\
         🔹 Send me a photo - I'll show file info and offer to resend it\n\
         🔹 Send me a document - I'll download and analyze it\n\
         🔹 /send_photo_url - Send photo from URL\n\
         🔹 /send_document - Generate and send text file\n\
         🔹 /send_album - Send photo album\n\
         🔹 /file_info - Info about last received file"
      in

      match reply ctx text with
      | Ok _ -> Eio.traceln "[/start] ✓"; Ok ()
      | Error e -> Eio.traceln "[/start] ✗ %a" Error.pp e; Ok ()
    )

  (* /send_photo_url - Send photo from URL *)
  |> Bot.command "send_photo_url" ~desc:"Send photo from URL" (fun ctx _args ->
      let open Bot.Ctx in
      Eio.traceln "[/send_photo_url] Sending photo from URL";

      (* Send photo from public URL *)
      let photo_url = "https://picsum.photos/800/600" in
      let chat_id = chat ctx in

      match Telegram_generated.Gen_methods.send_photo
        (client ctx)
        ~chat_id
        ~photo:photo_url
        ~caption:"📷 Photo from URL (https://picsum.photos)\n\nTelegram downloads this from the URL."
        () with
      | Ok _ -> Eio.traceln "[/send_photo_url] ✓"; Ok ()
      | Error e -> Eio.traceln "[/send_photo_url] ✗ %a" Error.pp e; Ok ()
    )

  (* /send_document - Generate and send text document *)
  |> Bot.command "send_document" ~desc:"Send generated text file" (fun ctx _args ->
      let open Bot.Ctx in
      Eio.traceln "[/send_document] Generating and sending document";

      (* Generate a simple text file *)
      let filename = Printf.sprintf "demo_%d.txt" (Unix.time () |> int_of_float) in
      let content = Printf.sprintf
        "Media Files Demo\n\
         Generated at: %s\n\n\
         This file was generated by the bot and sent as a document.\n\
         You can download it and see the contents."
        (Unix.time () |> int_of_float |> string_of_int)
      in

      (* Write to temporary file *)
      let temp_path = Filename.temp_file "tg_demo_" ".txt" in
      let oc = open_out temp_path in
      output_string oc content;
      close_out oc;

      Eio.traceln "[/send_document] Temp file: %s" temp_path;

      let chat_id = chat ctx in

      (match Telegram_generated.Gen_methods.send_document
        (client ctx)
        ~chat_id
        ~document:temp_path
        ~caption:(Printf.sprintf "📄 Generated file: %s" filename)
        () with
      | Ok _ ->
          Eio.traceln "[/send_document] ✓, cleaning up";
          Sys.remove temp_path;
          Ok ()
      | Error e ->
          Eio.traceln "[/send_document] ✗ %a" Error.pp e;
          Sys.remove temp_path;
          Ok ())
    )

  (* /send_album - Send photo album *)
  |> Bot.command "send_album" ~desc:"Send photo album from URLs" (fun ctx _args ->
      let open Bot.Ctx in
      Eio.traceln "[/send_album] Sending photo album";

      let chat_id = chat ctx in

      (* Create album with 3 photos from URLs *)
      let album =
        Album.create
          (Album.photo ~caption:"Photo 1: Random landscape" (Input_file.url "https://picsum.photos/800/600?random=1"))
          (Album.photo ~caption:"Photo 2: Another view" (Input_file.url "https://picsum.photos/800/600?random=2"))
        |> Album.add (Album.photo ~caption:"Photo 3: Final shot" (Input_file.url "https://picsum.photos/800/600?random=3"))
        |> Album.build
      in

      match Album.send (client ctx) ~chat_id album with
      | Ok messages ->
          Eio.traceln "[/send_album] Sent %d photos ✓" (List.length messages);
          Ok ()
      | Error e ->
          Eio.traceln "[/send_album] ✗ %a" Error.pp e;
          Ok ()
    )

  (* /file_info - Show info about last received file *)
  |> Bot.command "file_info" ~desc:"Show last file information" (fun ctx _args ->
      let open Bot.Ctx in
      Eio.traceln "[/file_info] Retrieving last file info";

      match session_get ctx last_photo_key with
      | Some file_id ->
          Eio.traceln "[/file_info] Found last photo: %s" file_id;

          (* Get file info from Telegram *)
          (match Download.get_file (client ctx) ~file_id with
           | Ok info ->
               Eio.traceln "[/file_info] File info retrieved";

               let size_str = match info.file_size with
                 | Some size -> Printf.sprintf "%Ld bytes (%.1f KB)" size (Int64.to_float size /. 1024.0)
                 | None -> "unknown"
               in

               let path_str = match info.file_path with
                 | Some path -> path
                 | None -> "<no path>"
               in

               let url = match Download.download_url_from_info (client ctx) info with
                 | Some u -> u
                 | None -> "<unavailable>"
               in

               let response = Printf.sprintf
                 "📋 File Information\n\n\
                  File ID: %s\n\
                  Unique ID: %s\n\
                  Size: %s\n\
                  Path: %s\n\
                  URL: %s\n\n\
                  (URL valid for 1 hour)"
                 file_id
                 info.file_unique_id
                 size_str
                 path_str
                 url
               in

               (match reply ctx response with
                | Ok _ -> Eio.traceln "[/file_info] ✓"; Ok ()
                | Error e -> Eio.traceln "[/file_info] ✗ %a" Error.pp e; Ok ())

           | Error e ->
               Eio.traceln "[/file_info] Failed to get file info: %a" Error.pp e;
               (match reply ctx "❌ Failed to retrieve file information" with
                | Ok _ -> Ok ()
                | Error e -> Eio.traceln "[/file_info] Reply error: %a" Error.pp e; Ok ()))

      | None ->
          Eio.traceln "[/file_info] No file stored in session";
          (match reply ctx "No file received yet. Send me a photo first!" with
           | Ok _ -> Ok ()
           | Error e -> Eio.traceln "[/file_info] ✗ %a" Error.pp e; Ok ())
    )

  (* Handle photo messages *)
  |> Bot.on_photo (fun ctx photos ->
      let open Bot.Ctx in
      Eio.traceln "[on_photo] Received %d photo sizes" (List.length photos);

      (* Get largest photo *)
      let largest = List.fold_left (fun acc p ->
        let open Telegram_generated.Gen_types.PhotoSize in
        let acc_size = Option.value acc.file_size ~default:0L in
        let p_size = Option.value p.file_size ~default:0L in
        if p_size > acc_size then p else acc
      ) (List.hd photos) photos
      in

      let open Telegram_generated.Gen_types.PhotoSize in
      let file_id = largest.file_id in

      (* Store file_id in session *)
      session_set ctx last_photo_key file_id;

      Eio.traceln "[on_photo] Stored file_id: %s" file_id;

      let size_kb = Int64.div (Option.value largest.file_size ~default:0L) 1024L in

      let keyboard = KB.inline [
        [KB.callback ~text:"🔄 Resend This Photo" ~data:(Printf.sprintf "resend_photo:%s" file_id)];
        [KB.callback ~text:"📋 Get File Info" ~data:"get_file_info"];
      ] in

      let response = Printf.sprintf
        "📷 Photo Received!\n\n\
         Sizes available: %d\n\
         Largest: %dx%d (%Ld KB)\n\
         File ID: %s\n\n\
         I've saved the file_id. You can resend it or get more info."
        (List.length photos)
        (Int64.to_int largest.width)
        (Int64.to_int largest.height)
        size_kb
        file_id
      in

      match reply ~keyboard ctx response with
      | Ok _ -> Eio.traceln "[on_photo] ✓"; Ok ()
      | Error e -> Eio.traceln "[on_photo] ✗ %a" Error.pp e; Ok ()
    )

  (* Handle document messages *)
  |> Bot.on_message (fun ctx msg ->
      let open Bot.Ctx in
      let open Telegram_generated.Gen_types.Message in

      match msg.document with
      | Some doc ->
          Eio.traceln "[on_document] Received document";

          let open Telegram_generated.Gen_types.Document in
          let file_id = doc.file_id in
          let filename = Option.value doc.file_name ~default:"<unknown>" in
          let size_kb = Int64.div (Option.value doc.file_size ~default:0L) 1024L in
          let mime = Option.value doc.mime_type ~default:"application/octet-stream" in

          (* Store file_id in session *)
          session_set ctx last_document_key file_id;

          Eio.traceln "[on_document] File: %s, Size: %Ld KB" filename size_kb;

          (* Try to download small files *)
          let download_result = if size_kb < 100L then (
            Eio.traceln "[on_document] Small file, attempting download";

            match Download.get_and_download_string (client ctx) ~file_id with
            | Ok contents ->
                Eio.traceln "[on_document] Downloaded %d bytes" (String.length contents);
                Some (String.length contents, String.sub contents 0 (min 100 (String.length contents)))
            | Error e ->
                Eio.traceln "[on_document] Download failed: %a" Error.pp e;
                None
          ) else None
          in

          let preview_text = match download_result with
            | Some (total_len, preview) ->
                Printf.sprintf
                  "\n\n📥 Downloaded %d bytes\n\nPreview:\n%s%s"
                  total_len
                  preview
                  (if total_len > 100 then "..." else "")
            | None ->
                if size_kb >= 100L then "\n\n(Too large to download in demo)"
                else "\n\n(Download failed)"
          in

          let response = Printf.sprintf
            "📄 Document Received!\n\n\
             Filename: %s\n\
             Size: %Ld KB\n\
             MIME: %s\n\
             File ID: %s%s"
            filename
            size_kb
            mime
            file_id
            preview_text
          in

          (match reply ctx response with
           | Ok _ -> Eio.traceln "[on_document] ✓"; Ok ()
           | Error e -> Eio.traceln "[on_document] ✗ %a" Error.pp e; Ok ())

      | None ->
          (* Not a document, skip *)
          Ok ()
    )

  (* Handle video messages *)
  |> Bot.on_message (fun ctx msg ->
      let open Bot.Ctx in
      let open Telegram_generated.Gen_types.Message in

      match msg.video with
      | Some video ->
          Eio.traceln "[on_video] Received video";

          let open Telegram_generated.Gen_types.Video in
          let size_mb = Int64.div (Option.value video.file_size ~default:0L) (Int64.mul 1024L 1024L) in

          let response = Printf.sprintf
            "🎥 Video Received!\n\n\
             Dimensions: %dx%d\n\
             Duration: %d seconds\n\
             Size: %Ld MB\n\
             MIME: %s\n\
             File ID: %s"
            (Int64.to_int video.width)
            (Int64.to_int video.height)
            (Int64.to_int video.duration)
            size_mb
            (Option.value video.mime_type ~default:"video/mp4")
            video.file_id
          in

          (match reply ctx response with
           | Ok _ -> Eio.traceln "[on_video] ✓"; Ok ()
           | Error e -> Eio.traceln "[on_video] ✗ %a" Error.pp e; Ok ())

      | None ->
          Ok ()
    )

  (* Callback: resend_photo *)
  |> Bot.on_callback (fun ctx data ->
      let open Bot.Ctx in

      if String.starts_with ~prefix:"resend_photo:" data then (
        let file_id = String.sub data 13 (String.length data - 13) in
        Eio.traceln "[resend_photo] Resending photo with file_id: %s" file_id;

        let chat_id = chat ctx in

        (* Resend using file_id (instant, no upload) *)
        match Telegram_generated.Gen_methods.send_photo
          (client ctx)
          ~chat_id
          ~photo:file_id
          ~caption:"🔄 Resent using file_id (instant, no upload!)"
          () with
        | Ok _ -> Eio.traceln "[resend_photo] ✓"; Ok ()
        | Error e -> Eio.traceln "[resend_photo] ✗ %a" Error.pp e; Ok ()
      ) else Ok ()
    )

  (* Callback: get_file_info *)
  |> Bot.on_callback_data "get_file_info" (fun ctx ->
      let open Bot.Ctx in
      Eio.traceln "[get_file_info] Retrieving file info";

      match session_get ctx last_photo_key with
      | Some file_id ->
          (* Get file info *)
          (match Download.get_file (client ctx) ~file_id with
           | Ok info ->
               let url = Download.download_url_from_info (client ctx) info in

               let text = Printf.sprintf
                 "📋 File Information\n\n\
                  File ID: %s\n\
                  Unique ID: %s\n\
                  Size: %s\n\
                  Download URL: %s"
                 file_id
                 info.file_unique_id
                 (match info.file_size with
                  | Some s -> Printf.sprintf "%Ld bytes" s
                  | None -> "unknown")
                 (match url with Some u -> u | None -> "<unavailable>")
               in

               (match edit ctx text with
                | Ok () -> Eio.traceln "[get_file_info] ✓"; Ok ()
                | Error e -> Eio.traceln "[get_file_info] ✗ %a" Error.pp e; Ok ())

           | Error e ->
               Eio.traceln "[get_file_info] ✗ %a" Error.pp e;
               Ok ())

      | None ->
          (match edit ctx "No photo stored. Send me a photo first!" with
           | Ok () -> Ok ()
           | Error e -> Eio.traceln "[get_file_info] ✗ %a" Error.pp e; Ok ())
    )

  |> Bot.run
