(library
 (name telegram)
 (public_name ocaml_telegram_eio.telegram)
 (libraries eio yojson cohttp-eio)
 (preprocess (pps ppx_deriving_yojson))
 (modules id types money units chat_action json_compat error client request api http version spec_ast spec_norm))

(library
 (name tg)
 (public_name ocaml_telegram_eio.tg)
 (libraries eio yojson ocaml_telegram_eio.telegram)
 (modules bot keyboard msg action session result_syntax))
